-- assets/scripts/tests/test_particle_builder.lua
local TestRunner = require("tests.test_runner")
local ParticleMock = require("tests.mocks.particle_mock")
local it, assert_equals, assert_not_nil = TestRunner.it, TestRunner.assert_equals, TestRunner.assert_not_nil

TestRunner.describe("Recipe", function()
    it("define() returns a Recipe object", function()
        local Particles = require("core.particles")
        local recipe = Particles.define()
        assert_not_nil(recipe, "define() should return a recipe")
        assert_not_nil(recipe._config, "recipe should have _config")
    end)

    it("shape() sets renderType for circle", function()
        local Particles = require("core.particles")
        local recipe = Particles.define():shape("circle")
        assert_equals("circle", recipe._config.shape)
    end)

    it("shape() sets renderType for rect", function()
        local Particles = require("core.particles")
        local recipe = Particles.define():shape("rect")
        assert_equals("rect", recipe._config.shape)
    end)

    it("shape() sets renderType for line", function()
        local Particles = require("core.particles")
        local recipe = Particles.define():shape("line")
        assert_equals("line", recipe._config.shape)
    end)

    it("shape() sets sprite with ID", function()
        local Particles = require("core.particles")
        local recipe = Particles.define():shape("sprite", "my_sprite")
        assert_equals("sprite", recipe._config.shape)
        assert_equals("my_sprite", recipe._config.spriteId)
    end)

    it("methods chain and return self", function()
        local Particles = require("core.particles")
        local recipe = Particles.define()
        local returned = recipe:shape("circle")
        assert_equals(recipe, returned, "shape() should return self for chaining")
    end)
end)

TestRunner.describe("Recipe properties", function()
    it("size() with single value", function()
        local Particles = require("core.particles")
        local recipe = Particles.define():size(6)
        assert_equals(6, recipe._config.sizeMin)
        assert_equals(6, recipe._config.sizeMax)
    end)

    it("size() with range", function()
        local Particles = require("core.particles")
        local recipe = Particles.define():size(4, 8)
        assert_equals(4, recipe._config.sizeMin)
        assert_equals(8, recipe._config.sizeMax)
    end)

    it("color() with single color", function()
        local Particles = require("core.particles")
        local recipe = Particles.define():color("red")
        assert_equals("red", recipe._config.startColor)
        assert_equals("red", recipe._config.endColor)
    end)

    it("color() with start and end", function()
        local Particles = require("core.particles")
        local recipe = Particles.define():color("orange", "red")
        assert_equals("orange", recipe._config.startColor)
        assert_equals("red", recipe._config.endColor)
    end)

    it("lifespan() with single value", function()
        local Particles = require("core.particles")
        local recipe = Particles.define():lifespan(0.5)
        assert_equals(0.5, recipe._config.lifespanMin)
        assert_equals(0.5, recipe._config.lifespanMax)
    end)

    it("lifespan() with range", function()
        local Particles = require("core.particles")
        local recipe = Particles.define():lifespan(0.3, 0.6)
        assert_equals(0.3, recipe._config.lifespanMin)
        assert_equals(0.6, recipe._config.lifespanMax)
    end)
end)

TestRunner.describe("Recipe motion", function()
    it("velocity() with single value", function()
        local Particles = require("core.particles")
        local recipe = Particles.define():velocity(100)
        assert_equals(100, recipe._config.velocityMin)
        assert_equals(100, recipe._config.velocityMax)
    end)

    it("velocity() with range", function()
        local Particles = require("core.particles")
        local recipe = Particles.define():velocity(100, 200)
        assert_equals(100, recipe._config.velocityMin)
        assert_equals(200, recipe._config.velocityMax)
    end)

    it("gravity() sets gravity strength", function()
        local Particles = require("core.particles")
        local recipe = Particles.define():gravity(200)
        assert_equals(200, recipe._config.gravity)
    end)

    it("drag() sets drag factor", function()
        local Particles = require("core.particles")
        local recipe = Particles.define():drag(0.95)
        assert_equals(0.95, recipe._config.drag)
    end)
end)

return function()
    TestRunner.run_all()
end
