---@meta
-- Generated by scripts/generate_stubs.py. DO NOT EDIT BY HAND.

Blackboard = Blackboard or {}
ai = ai or {}
bb = bb or {}
sense = sense or {}

---@class Blackboard
Blackboard = Blackboard or {}

---@class ai
ai = ai or {}

---@param ... any
---@return any
function ai.clear_trace(...) end

---@param ... any
---@return any
function ai.dump_blackboard(...) end

---@param ... any
---@return any
function ai.dump_plan(...) end

---@param ... any
---@return any
function ai.dump_worldstate(...) end

---@param ... any
---@return any
function ai.force_interrupt(...) end

---@param ... any
---@return any
function ai.get_all_atoms(...) end

---@param ... any
---@return any
function ai.get_blackboard(...) end

---@param ... any
---@return any
function ai.get_entity_ai_def(...) end

---@param ... any
---@return any
function ai.get_goap_state(...) end

---@param ... any
---@return any
function ai.get_trace_events(...) end

---@param ... any
---@return any
function ai.get_worldstate(...) end

---@param ... any
---@return any
function ai.has_plan(...) end

---@param ... any
---@return any
function ai.list_goap_entities(...) end

---@param ... any
---@return any
function ai.list_lua_files(...) end

---@param ... any
---@return any
function ai.patch_goal(...) end

---@param ... any
---@return any
function ai.patch_worldstate(...) end

---@param ... any
---@return any
function ai.pause_ai_system(...) end

---@param ... any
---@return any
function ai.report_goal_selection(...) end

---@param ... any
---@return any
function ai.resume_ai_system(...) end

---@param ... any
---@return any
function ai.set_goal(...) end

---@param ... any
---@return any
function ai.set_worldstate(...) end

---@param ... any
---@return any
function bb.clear(...) end

---@param ... any
---@return any
function bb.decay(...) end

---@param ... any
---@return any
function bb.get(...) end

---@param ... any
---@return any
function bb.get_vec2(...) end

---@param ... any
---@return any
function bb.has(...) end

---@param ... any
---@return any
function bb.inc(...) end

---@param ... any
---@return any
function bb.set(...) end

---@param ... any
---@return any
function bb.set_vec2(...) end

---@param ... any
---@return any
function create_ai_entity(...) end

---@param ... any
---@return any
function create_ai_entity_with_overrides(...) end

---@param ... any
---@return any
function sense.all_in_range(...) end

---@param ... any
---@return any
function sense.distance(...) end

---@param ... any
---@return any
function sense.nearest(...) end

---@param ... any
---@return any
function sense.position(...) end
