---@meta
-- Generated by scripts/generate_stubs.py. DO NOT EDIT BY HAND.

AnimationQueueComponent = AnimationQueueComponent or {}
Blackboard = Blackboard or {}
Box = Box or {}
Camera2D = Camera2D or {}
Entity = Entity or {}
L = L or {}
WorldQuadtree = WorldQuadtree or {}
ai = ai or {}
animation_system = animation_system or {}
bb = bb or {}
component_cache = component_cache or {}
entt = entt or {}
globals = globals or {}
layers = layers or {}
ownership_table = ownership_table or {}
qmod = qmod or {}
quadtree = quadtree or {}
sense = sense or {}
L.WorldQuadtree = L.WorldQuadtree or {}
entt.registry = entt.registry or {}
entt.runtime_view = entt.runtime_view or {}

---@class AnimationQueueComponent
AnimationQueueComponent = AnimationQueueComponent or {}

---@class Blackboard
Blackboard = Blackboard or {}

---@class Box
---@field height any
---@field left any
---@field top any
---@field width any
Box = Box or {}

---@class Camera2D
---@field offset any
---@field rotation any
---@field target any
---@field zoom any
Camera2D = Camera2D or {}

---@class Entity
Entity = Entity or {}

---@class L.WorldQuadtree
L.WorldQuadtree = L.WorldQuadtree or {}

---@class WorldQuadtree
WorldQuadtree = WorldQuadtree or {}

---@class ai
ai = ai or {}

---@class animation_system
animation_system = animation_system or {}

---@class entt.registry
---@field add_script any
---@field alive any
---@field any_of any
---@field clear any
---@field create any
---@field current any
---@field destroy any
---@field emplace any
---@field get any
---@field has any
---@field new any
---@field orphan any
---@field remove any
---@field runtime_view any
---@field size any
---@field valid any
entt.registry = entt.registry or {}

---@class entt.runtime_view
---@field contains any
---@field each any
---@field size_hint any
entt.runtime_view = entt.runtime_view or {}

---@class globals
---@field camera any
---@field currentGameState any
---@field cursor any
---@field gameWorldContainerEntity any
---@field inputState any
---@field isGamePaused any
---@field screenHeight any
---@field screenWidth any
---@field screenWipe any
globals = globals or {}

---@class layers
layers = layers or {}

---@class quadtree
quadtree = quadtree or {}

---@return number
function GetFrameTime() end

---@param ... any
---@return any
function GetLayer(...) end

---@return integer
function GetScreenHeight() end

---@param position Vector2
---@param camera Camera2D
---@return Vector2
function GetScreenToWorld2D(position, camera) end

---@return integer
function GetScreenWidth() end

---@return number
function GetTime() end

---@param position Vector2
---@param camera Camera2D
---@return Vector2
function GetWorldToScreen2D(position, camera) end

---@param ... any
---@return any
function OpenURL(...) end

---@param ... any
---@return any
function Vector2(...) end

---@param ... any
---@return any
function Vector3(...) end

---@param ... any
---@return any
function Vector4(...) end

---@param ... any
---@return any
function add_layer_shader(...) end

---@param ... any
---@return any
function ai.clear_trace(...) end

---@param ... any
---@return any
function ai.dump_blackboard(...) end

---@param ... any
---@return any
function ai.dump_plan(...) end

---@param ... any
---@return any
function ai.dump_worldstate(...) end

---@param ... any
---@return any
function ai.force_interrupt(...) end

---@param ... any
---@return any
function ai.get_all_atoms(...) end

---@param ... any
---@return any
function ai.get_blackboard(...) end

---@param ... any
---@return any
function ai.get_entity_ai_def(...) end

---@param ... any
---@return any
function ai.get_goap_state(...) end

---@param ... any
---@return any
function ai.get_trace_events(...) end

---@param ... any
---@return any
function ai.get_worldstate(...) end

---@param ... any
---@return any
function ai.has_plan(...) end

---@param ... any
---@return any
function ai.list_goap_entities(...) end

---@param ... any
---@return any
function ai.list_lua_files(...) end

---@param ... any
---@return any
function ai.patch_goal(...) end

---@param ... any
---@return any
function ai.patch_worldstate(...) end

---@param ... any
---@return any
function ai.pause_ai_system(...) end

---@param ... any
---@return any
function ai.report_goal_selection(...) end

---@param ... any
---@return any
function ai.resume_ai_system(...) end

---@param ... any
---@return any
function ai.set_goal(...) end

---@param ... any
---@return any
function ai.set_worldstate(...) end

---@param ... any
---@return any
function bb.clear(...) end

---@param ... any
---@return any
function bb.decay(...) end

---@param ... any
---@return any
function bb.get(...) end

---@param ... any
---@return any
function bb.get_vec2(...) end

---@param ... any
---@return any
function bb.has(...) end

---@param ... any
---@return any
function bb.inc(...) end

---@param ... any
---@return any
function bb.set(...) end

---@param ... any
---@return any
function bb.set_vec2(...) end

---@param ... any
---@return any
function clearCallbacks(...) end

---@param ... any
---@return any
function clear_layer_shaders(...) end

---@param entity any
---@param component_type any
---@return table|nil
function component_cache.get(entity, component_type) end

---@param entity any
---@param component_type any
---@return nil
function component_cache.invalidate(entity, component_type) end

---@param ... any
---@return any
function createAnimatedObjectWithTransform(...) end

---@param ... any
---@return any
function createStillAnimationFromSpriteUUID(...) end

---@param ... any
---@return any
function create_ai_entity(...) end

---@param ... any
---@return any
function create_ai_entity_with_overrides(...) end

---@param ... any
---@return any
function getCurrentFrame(...) end

---@param ... any
---@return any
function getEntityByAlias(...) end

---@param ... any
---@return any
function getFrameCount(...) end

---@param ... any
---@return any
function getNinepatchUIBorderInfo(...) end

---@param ... any
---@return any
function getProgress(...) end

---@param ... any
---@return any
function getSpriteFrameTextureInfo(...) end

---@param ... any
---@return any
function get_shader_texture_batching(...) end

---@param ... any
---@return any
function isKeyPressed(...) end

---@param ... any
---@return any
function isPlaying(...) end

---@param ... any
---@return any
function log_debug(...) end

---@param ... any
---@return any
function log_error(...) end

---@param ... any
---@return any
function log_info(...) end

---@param ... any
---@return any
function log_warn(...) end

---@param ... any
---@return any
function onAnimationEnd(...) end

---@param ... any
---@return any
function onFrameChange(...) end

---@param ... any
---@return any
function onLoopComplete(...) end

---@param ... any
---@return any
function ownership_table.getBuildId(...) end

---@param ... any
---@return any
function ownership_table.getBuildSignature(...) end

---@param ... any
---@return any
function ownership_table.getDiscordLink(...) end

---@param ... any
---@return any
function ownership_table.getItchLink(...) end

---@param ... any
---@return any
function ownership_table.validate(...) end

---@param ... any
---@return any
function pause(...) end

---@param ... any
---@return any
function pauseGame(...) end

---@param ... any
---@return any
function play(...) end

---@param ... any
---@return any
function qmod.box(...) end

---@param ... any
---@return any
function remove_layer_shader(...) end

---@param ... any
---@return any
function replaceAnimatedObjectOnEntity(...) end

---@param ... any
---@return any
function resetAnimationUIRenderScale(...) end

---@param ... any
---@return any
function resizeAnimationObjectToFit(...) end

---@param ... any
---@return any
function resizeAnimationObjectsInEntityToFit(...) end

---@param ... any
---@return any
function resizeAnimationObjectsInEntityToFitAndCenterUI(...) end

---@param ... any
---@return any
function seekFrame(...) end

---@param ... any
---@return any
function sense.all_in_range(...) end

---@param ... any
---@return any
function sense.distance(...) end

---@param ... any
---@return any
function sense.nearest(...) end

---@param ... any
---@return any
function sense.position(...) end

---@param ... any
---@return any
function setDirection(...) end

---@param ... any
---@return any
function setEntityAlias(...) end

---@param ... any
---@return any
function setFGColorForAllAnimationObjects(...) end

---@param ... any
---@return any
function setLoopCount(...) end

---@param ... any
---@return any
function setPaletteTexture(...) end

---@param ... any
---@return any
function setSpeed(...) end

---@param ... any
---@return any
function set_flip(...) end

---@param ... any
---@return any
function set_horizontal_flip(...) end

---@param ... any
---@return any
function set_shader_texture_batching(...) end

---@param ... any
---@return any
function setupAnimatedObjectOnEntity(...) end

---@param ... any
---@return any
function stop(...) end

---@param ... any
---@return any
function toggle_flip(...) end

---@param ... any
---@return any
function unpauseGame(...) end

---@param ... any
---@return any
function update(...) end
