---@meta
-- Generated by scripts/generate_stubs.py. DO NOT EDIT BY HAND.

AxisButtonState = AxisButtonState or {}
CursorContext = CursorContext or {}
CursorLayer = CursorLayer or {}
GamepadAxis = GamepadAxis or {}
GamepadButton = GamepadButton or {}
GamepadState = GamepadState or {}
HIDFlags = HIDFlags or {}
InputDeviceInputCategory = InputDeviceInputCategory or {}
InputState = InputState or {}
KeyboardKey = KeyboardKey or {}
L = L or {}
MouseButton = MouseButton or {}
NodeData = NodeData or {}
SnapTarget = SnapTarget or {}
in = in or {}
CursorContext.CursorLayer = CursorContext.CursorLayer or {}
L.HIDFlags = L.HIDFlags or {}
L.InputState = L.InputState or {}

---@class AxisButtonState
---@field current any
---@field previous any
AxisButtonState = AxisButtonState or {}

---@class CursorContext
---@field layer any
---@field stack any
CursorContext = CursorContext or {}

---@class CursorContext.CursorLayer
---@field cursor_focused_target any
---@field cursor_position any
---@field focus_interrupt any
CursorContext.CursorLayer = CursorContext.CursorLayer or {}

---@class CursorLayer
CursorLayer = CursorLayer or {}

---@enum GamepadAxis
GamepadAxis = GamepadAxis or {}

---@enum GamepadButton
GamepadButton = GamepadButton or {}

---@class GamepadState
---@field console any
---@field id any
---@field mapping any
---@field name any
---@field object any
GamepadState = GamepadState or {}

---@class HIDFlags
---@field axis_cursor_enabled any
---@field controller_enabled any
---@field dpad_enabled any
---@field last_type any
---@field mouse_enabled any
---@field pointer_enabled any
---@field touch_enabled any
HIDFlags = HIDFlags or {}

---@enum InputDeviceInputCategory
---@field GAMEPAD_AXIS any
---@field GAMEPAD_AXIS_CURSOR any
---@field GAMEPAD_BUTTON any
---@field MOUSE any
---@field NONE any
---@field TOUCH any
InputDeviceInputCategory = InputDeviceInputCategory or {}

---@class InputState
InputState = InputState or {}

---@enum KeyboardKey
KeyboardKey = KeyboardKey or {}

---@class L.HIDFlags
L.HIDFlags = L.HIDFlags or {}

---@class L.InputState
L.InputState = L.InputState or {}

---@enum MouseButton
---@field MOUSE_BUTTON_BACK any
---@field MOUSE_BUTTON_EXTRA any
---@field MOUSE_BUTTON_FORWARD any
---@field MOUSE_BUTTON_LEFT any
---@field MOUSE_BUTTON_MIDDLE any
---@field MOUSE_BUTTON_RIGHT any
---@field MOUSE_BUTTON_SIDE any
MouseButton = MouseButton or {}

---@class NodeData
---@field click any
---@field menu any
---@field node any
---@field under_overlay any
NodeData = NodeData or {}

---@class SnapTarget
---@field node any
---@field transform any
---@field type any
SnapTarget = SnapTarget or {}

---@param ... any
---@return any
function in.action_down(...) end

---@param ... any
---@return any
function in.action_pressed(...) end

---@param ... any
---@return any
function in.action_released(...) end

---@param ... any
---@return any
function in.action_value(...) end

---@param ... any
---@return any
function in.bind(...) end

---@param ... any
---@return any
function in.clear(...) end

---@param ... any
---@return any
function in.clearActiveScrollPane(...) end

---@param ... any
---@return any
function in.getChar(...) end

---@param ... any
---@return any
function in.getKeyPressed(...) end

---@param ... any
---@return any
function in.getMousePos(...) end

---@param ... any
---@return any
function in.getMouseWheel(...) end

---@param ... any
---@return any
function in.getPadAxis(...) end

---@param ... any
---@return any
function in.getState(...) end

---@param ... any
---@return any
function in.isGamepadEnabled(...) end

---@param ... any
---@return any
function in.isKeyDown(...) end

---@param ... any
---@return any
function in.isKeyPressed(...) end

---@param ... any
---@return any
function in.isKeyReleased(...) end

---@param ... any
---@return any
function in.isKeyUp(...) end

---@param ... any
---@return any
function in.isMouseDown(...) end

---@param ... any
---@return any
function in.isMousePressed(...) end

---@param ... any
---@return any
function in.isMouseReleased(...) end

---@param ... any
---@return any
function in.isPadButtonDown(...) end

---@param ... any
---@return any
function in.isPadConnected(...) end

---@param ... any
---@return any
function in.setExitKey(...) end

---@param ... any
---@return any
function in.set_context(...) end

---@param ... any
---@return any
function in.start_rebind(...) end

---@param ... any
---@return any
function in.updateCursorFocus(...) end
