---@meta
-- Generated by scripts/generate_stubs.py. DO NOT EDIT BY HAND.

GL_ALWAYS = GL_ALWAYS or {}
GL_EQUAL = GL_EQUAL or {}
GL_FALSE = GL_FALSE or {}
GL_KEEP = GL_KEEP or {}
GL_REPLACE = GL_REPLACE or {}
GL_ZERO = GL_ZERO or {}
NPatchInfo = NPatchInfo or {}
Rectangle = Rectangle or {}
cb = cb or {}
command_buffer = command_buffer or {}
layer = layer or {}
layerTbl = layerTbl or {}
npatchTbl = npatchTbl or {}
rectTbl = rectTbl or {}
rectUT = rectUT or {}
layer.CmdAddPop = layer.CmdAddPop or {}
layer.CmdAddPush = layer.CmdAddPush or {}
layer.CmdAtomicStencilMask = layer.CmdAtomicStencilMask or {}
layer.CmdBeginDrawing = layer.CmdBeginDrawing or {}
layer.CmdBeginOpenGLMode = layer.CmdBeginOpenGLMode or {}
layer.CmdBeginScissorMode = layer.CmdBeginScissorMode or {}
layer.CmdBeginStencilMask = layer.CmdBeginStencilMask or {}
layer.CmdBeginStencilMode = layer.CmdBeginStencilMode or {}
layer.CmdClearBackground = layer.CmdClearBackground or {}
layer.CmdClearStencilBuffer = layer.CmdClearStencilBuffer or {}
layer.CmdColorMask = layer.CmdColorMask or {}
layer.CmdDrawArc = layer.CmdDrawArc or {}
layer.CmdDrawBatchedEntities = layer.CmdDrawBatchedEntities or {}
layer.CmdDrawCenteredEllipse = layer.CmdDrawCenteredEllipse or {}
layer.CmdDrawCenteredFilledRoundedRect = layer.CmdDrawCenteredFilledRoundedRect or {}
layer.CmdDrawCircleFilled = layer.CmdDrawCircleFilled or {}
layer.CmdDrawCircleLine = layer.CmdDrawCircleLine or {}
layer.CmdDrawDashedCircle = layer.CmdDrawDashedCircle or {}
layer.CmdDrawDashedLine = layer.CmdDrawDashedLine or {}
layer.CmdDrawDashedRoundedRect = layer.CmdDrawDashedRoundedRect or {}
layer.CmdDrawEntityAnimation = layer.CmdDrawEntityAnimation or {}
layer.CmdDrawGradientRectCentered = layer.CmdDrawGradientRectCentered or {}
layer.CmdDrawGradientRectRoundedCentered = layer.CmdDrawGradientRectRoundedCentered or {}
layer.CmdDrawImage = layer.CmdDrawImage or {}
layer.CmdDrawLine = layer.CmdDrawLine or {}
layer.CmdDrawPolygon = layer.CmdDrawPolygon or {}
layer.CmdDrawPolyline = layer.CmdDrawPolyline or {}
layer.CmdDrawRectangle = layer.CmdDrawRectangle or {}
layer.CmdDrawRectangleLinesPro = layer.CmdDrawRectangleLinesPro or {}
layer.CmdDrawRectanglePro = layer.CmdDrawRectanglePro or {}
layer.CmdDrawRoundedLine = layer.CmdDrawRoundedLine or {}
layer.CmdDrawSpriteCentered = layer.CmdDrawSpriteCentered or {}
layer.CmdDrawSpriteTopLeft = layer.CmdDrawSpriteTopLeft or {}
layer.CmdDrawSteppedRoundedRect = layer.CmdDrawSteppedRoundedRect or {}
layer.CmdDrawText = layer.CmdDrawText or {}
layer.CmdDrawTextCentered = layer.CmdDrawTextCentered or {}
layer.CmdDrawTransformEntityAnimation = layer.CmdDrawTransformEntityAnimation or {}
layer.CmdDrawTransformEntityAnimationPipeline = layer.CmdDrawTransformEntityAnimationPipeline or {}
layer.CmdDrawTriangle = layer.CmdDrawTriangle or {}
layer.CmdDrawTriangleEquilateral = layer.CmdDrawTriangleEquilateral or {}
layer.CmdEndDrawing = layer.CmdEndDrawing or {}
layer.CmdEndOpenGLMode = layer.CmdEndOpenGLMode or {}
layer.CmdEndScissorMode = layer.CmdEndScissorMode or {}
layer.CmdEndStencilMask = layer.CmdEndStencilMask or {}
layer.CmdEndStencilMode = layer.CmdEndStencilMode or {}
layer.CmdPopMatrix = layer.CmdPopMatrix or {}
layer.CmdPushMatrix = layer.CmdPushMatrix or {}
layer.CmdPushObjectTransformsToMatrix = layer.CmdPushObjectTransformsToMatrix or {}
layer.CmdRenderBatchFlush = layer.CmdRenderBatchFlush or {}
layer.CmdRenderNPatchRect = layer.CmdRenderNPatchRect or {}
layer.CmdRenderRectVerticesFilledLayer = layer.CmdRenderRectVerticesFilledLayer or {}
layer.CmdRenderRectVerticesOutlineLayer = layer.CmdRenderRectVerticesOutlineLayer or {}
layer.CmdResetShader = layer.CmdResetShader or {}
layer.CmdRotate = layer.CmdRotate or {}
layer.CmdScale = layer.CmdScale or {}
layer.CmdScopedTransformCompositeRender = layer.CmdScopedTransformCompositeRender or {}
layer.CmdSendUniformFloat = layer.CmdSendUniformFloat or {}
layer.CmdSendUniformFloatArray = layer.CmdSendUniformFloatArray or {}
layer.CmdSendUniformInt = layer.CmdSendUniformInt or {}
layer.CmdSendUniformIntArray = layer.CmdSendUniformIntArray or {}
layer.CmdSendUniformVec2 = layer.CmdSendUniformVec2 or {}
layer.CmdSendUniformVec3 = layer.CmdSendUniformVec3 or {}
layer.CmdSendUniformVec4 = layer.CmdSendUniformVec4 or {}
layer.CmdSetBlendMode = layer.CmdSetBlendMode or {}
layer.CmdSetColor = layer.CmdSetColor or {}
layer.CmdSetLineWidth = layer.CmdSetLineWidth or {}
layer.CmdSetShader = layer.CmdSetShader or {}
layer.CmdSetTexture = layer.CmdSetTexture or {}
layer.CmdStencilFunc = layer.CmdStencilFunc or {}
layer.CmdStencilOp = layer.CmdStencilOp or {}
layer.CmdTextPro = layer.CmdTextPro or {}
layer.CmdTexturePro = layer.CmdTexturePro or {}
layer.CmdTranslate = layer.CmdTranslate or {}
layer.CmdUnsetBlendMode = layer.CmdUnsetBlendMode or {}
layer.CmdVertex = layer.CmdVertex or {}
layer.DrawCommandSpace = layer.DrawCommandSpace or {}
layer.DrawCommandType = layer.DrawCommandType or {}
layer.DrawCommandV2 = layer.DrawCommandV2 or {}
layer.Layer = layer.Layer or {}
layer.LayerOrderComponent = layer.LayerOrderComponent or {}
layerTbl.CmdResetShader = layerTbl.CmdResetShader or {}
layerTbl.DrawCommandType = layerTbl.DrawCommandType or {}
layerTbl.DrawCommandV2 = layerTbl.DrawCommandV2 or {}
layerTbl.Layer = layerTbl.Layer or {}
layerTbl.LayerOrderComponent = layerTbl.LayerOrderComponent or {}

---@class GL_ALWAYS
GL_ALWAYS = GL_ALWAYS or {}

---@class GL_EQUAL
GL_EQUAL = GL_EQUAL or {}

---@class GL_FALSE
GL_FALSE = GL_FALSE or {}

---@class GL_KEEP
GL_KEEP = GL_KEEP or {}

---@class GL_REPLACE
GL_REPLACE = GL_REPLACE or {}

---@class GL_ZERO
GL_ZERO = GL_ZERO or {}

---@class NPatchInfo
---@field bottom any
---@field layout any
---@field left any
---@field right any
---@field source any
---@field top any
NPatchInfo = NPatchInfo or {}

---@class Rectangle
---@field height any
---@field width any
---@field x any
---@field y any
Rectangle = Rectangle or {}

---@class command_buffer
command_buffer = command_buffer or {}

---@class layer
---@field layers any
layer = layer or {}

---@class layer.CmdAddPop
---@field dummy any
layer.CmdAddPop = layer.CmdAddPop or {}

---@class layer.CmdAddPush
---@field camera any
layer.CmdAddPush = layer.CmdAddPush or {}

---@class layer.CmdAtomicStencilMask
---@field mask any
layer.CmdAtomicStencilMask = layer.CmdAtomicStencilMask or {}

---@class layer.CmdBeginDrawing
---@field dummy any
layer.CmdBeginDrawing = layer.CmdBeginDrawing or {}

---@class layer.CmdBeginOpenGLMode
---@field mode any
layer.CmdBeginOpenGLMode = layer.CmdBeginOpenGLMode or {}

---@class layer.CmdBeginScissorMode
---@field area any
layer.CmdBeginScissorMode = layer.CmdBeginScissorMode or {}

---@class layer.CmdBeginStencilMask
---@field dummy any
layer.CmdBeginStencilMask = layer.CmdBeginStencilMask or {}

---@class layer.CmdBeginStencilMode
---@field dummy any
layer.CmdBeginStencilMode = layer.CmdBeginStencilMode or {}

---@class layer.CmdClearBackground
---@field color any
layer.CmdClearBackground = layer.CmdClearBackground or {}

---@class layer.CmdClearStencilBuffer
---@field dummy any
layer.CmdClearStencilBuffer = layer.CmdClearStencilBuffer or {}

---@class layer.CmdColorMask
---@field a any
---@field b any
---@field g any
---@field r any
layer.CmdColorMask = layer.CmdColorMask or {}

---@class layer.CmdDrawArc
---@field color any
---@field lineWidth any
---@field r any
---@field r1 any
---@field r2 any
---@field segments any
---@field type any
---@field x any
---@field y any
layer.CmdDrawArc = layer.CmdDrawArc or {}

---@class layer.CmdDrawBatchedEntities
---@field autoOptimize any
---@field entities any
---@field registry any
layer.CmdDrawBatchedEntities = layer.CmdDrawBatchedEntities or {}

---@class layer.CmdDrawCenteredEllipse
---@field color any
---@field lineWidth any
---@field rx any
---@field ry any
---@field x any
---@field y any
layer.CmdDrawCenteredEllipse = layer.CmdDrawCenteredEllipse or {}

---@class layer.CmdDrawCenteredFilledRoundedRect
---@field color any
---@field h any
---@field lineWidth any
---@field rx any
---@field ry any
---@field w any
---@field x any
---@field y any
layer.CmdDrawCenteredFilledRoundedRect = layer.CmdDrawCenteredFilledRoundedRect or {}

---@class layer.CmdDrawCircleFilled
---@field color any
---@field radius any
---@field x any
---@field y any
layer.CmdDrawCircleFilled = layer.CmdDrawCircleFilled or {}

---@class layer.CmdDrawCircleLine
---@field color any
---@field endAngle any
---@field innerRadius any
---@field outerRadius any
---@field segments any
---@field startAngle any
---@field x any
---@field y any
layer.CmdDrawCircleLine = layer.CmdDrawCircleLine or {}

---@class layer.CmdDrawDashedCircle
---@field center any
---@field color any
---@field dashLength any
---@field gapLength any
---@field phase any
---@field radius any
---@field segments any
---@field thickness any
layer.CmdDrawDashedCircle = layer.CmdDrawDashedCircle or {}

---@class layer.CmdDrawDashedLine
---@field color any
---@field dashLength any
---@field dashSize any
---@field endPoint any
---@field gapLength any
---@field gapSize any
---@field lineWidth any
---@field phase any
---@field start any
---@field thickness any
---@field x1 any
---@field x2 any
---@field y1 any
---@field y2 any
layer.CmdDrawDashedLine = layer.CmdDrawDashedLine or {}

---@class layer.CmdDrawDashedRoundedRect
---@field arcSteps any
---@field color any
---@field dashLen any
---@field gapLen any
---@field phase any
---@field radius any
---@field rec any
---@field thickness any
layer.CmdDrawDashedRoundedRect = layer.CmdDrawDashedRoundedRect or {}

---@class layer.CmdDrawEntityAnimation
---@field e any
---@field registry any
---@field x any
---@field y any
layer.CmdDrawEntityAnimation = layer.CmdDrawEntityAnimation or {}

---@class layer.CmdDrawGradientRectCentered
---@field bottomLeft any
---@field bottomRight any
---@field cx any
---@field cy any
---@field height any
---@field topLeft any
---@field topRight any
---@field width any
layer.CmdDrawGradientRectCentered = layer.CmdDrawGradientRectCentered or {}

---@class layer.CmdDrawGradientRectRoundedCentered
---@field bottomLeft any
---@field bottomRight any
---@field cx any
---@field cy any
---@field height any
---@field roundness any
---@field segments any
---@field topLeft any
---@field topRight any
---@field width any
layer.CmdDrawGradientRectRoundedCentered = layer.CmdDrawGradientRectRoundedCentered or {}

---@class layer.CmdDrawImage
---@field color any
---@field image any
---@field rotation any
---@field scaleX any
---@field scaleY any
---@field x any
---@field y any
layer.CmdDrawImage = layer.CmdDrawImage or {}

---@class layer.CmdDrawLine
---@field color any
---@field lineWidth any
---@field x1 any
---@field x2 any
---@field y1 any
---@field y2 any
layer.CmdDrawLine = layer.CmdDrawLine or {}

---@class layer.CmdDrawPolygon
---@field color any
---@field lineWidth any
---@field vertices any
layer.CmdDrawPolygon = layer.CmdDrawPolygon or {}

---@class layer.CmdDrawPolyline
---@field color any
---@field lineWidth any
---@field points any
layer.CmdDrawPolyline = layer.CmdDrawPolyline or {}

---@class layer.CmdDrawRectangle
---@field color any
---@field height any
---@field lineWidth any
---@field width any
---@field x any
---@field y any
layer.CmdDrawRectangle = layer.CmdDrawRectangle or {}

---@class layer.CmdDrawRectangleLinesPro
---@field color any
---@field lineThickness any
---@field offsetX any
---@field offsetY any
---@field size any
layer.CmdDrawRectangleLinesPro = layer.CmdDrawRectangleLinesPro or {}

---@class layer.CmdDrawRectanglePro
---@field color any
---@field offsetX any
---@field offsetY any
---@field rotation any
---@field rotationCenter any
---@field size any
layer.CmdDrawRectanglePro = layer.CmdDrawRectanglePro or {}

---@class layer.CmdDrawRoundedLine
---@field color any
---@field lineWidth any
---@field x1 any
---@field x2 any
---@field y1 any
---@field y2 any
layer.CmdDrawRoundedLine = layer.CmdDrawRoundedLine or {}

---@class layer.CmdDrawSpriteCentered
---@field dstH any
---@field dstW any
---@field spriteName any
---@field tint any
---@field x any
---@field y any
layer.CmdDrawSpriteCentered = layer.CmdDrawSpriteCentered or {}

---@class layer.CmdDrawSpriteTopLeft
---@field dstH any
---@field dstW any
---@field spriteName any
---@field tint any
---@field x any
---@field y any
layer.CmdDrawSpriteTopLeft = layer.CmdDrawSpriteTopLeft or {}

---@class layer.CmdDrawSteppedRoundedRect
---@field borderColor any
---@field borderWidth any
---@field fillColor any
---@field h any
---@field numSteps any
---@field w any
---@field x any
---@field y any
layer.CmdDrawSteppedRoundedRect = layer.CmdDrawSteppedRoundedRect or {}

---@class layer.CmdDrawText
---@field color any
---@field font any
---@field fontSize any
---@field text any
---@field x any
---@field y any
layer.CmdDrawText = layer.CmdDrawText or {}

---@class layer.CmdDrawTextCentered
---@field color any
---@field font any
---@field fontSize any
---@field text any
---@field x any
---@field y any
layer.CmdDrawTextCentered = layer.CmdDrawTextCentered or {}

---@class layer.CmdDrawTransformEntityAnimation
---@field e any
---@field registry any
layer.CmdDrawTransformEntityAnimation = layer.CmdDrawTransformEntityAnimation or {}

---@class layer.CmdDrawTransformEntityAnimationPipeline
---@field e any
---@field registry any
layer.CmdDrawTransformEntityAnimationPipeline = layer.CmdDrawTransformEntityAnimationPipeline or {}

---@class layer.CmdDrawTriangle
---@field color any
---@field p1 any
---@field p2 any
---@field p3 any
layer.CmdDrawTriangle = layer.CmdDrawTriangle or {}

---@class layer.CmdDrawTriangleEquilateral
---@field color any
---@field lineWidth any
---@field w any
---@field x any
---@field y any
layer.CmdDrawTriangleEquilateral = layer.CmdDrawTriangleEquilateral or {}

---@class layer.CmdEndDrawing
---@field dummy any
layer.CmdEndDrawing = layer.CmdEndDrawing or {}

---@class layer.CmdEndOpenGLMode
---@field dummy any
layer.CmdEndOpenGLMode = layer.CmdEndOpenGLMode or {}

---@class layer.CmdEndScissorMode
---@field dummy any
layer.CmdEndScissorMode = layer.CmdEndScissorMode or {}

---@class layer.CmdEndStencilMask
---@field dummy any
layer.CmdEndStencilMask = layer.CmdEndStencilMask or {}

---@class layer.CmdEndStencilMode
---@field dummy any
layer.CmdEndStencilMode = layer.CmdEndStencilMode or {}

---@class layer.CmdPopMatrix
---@field dummy any
layer.CmdPopMatrix = layer.CmdPopMatrix or {}

---@class layer.CmdPushMatrix
---@field dummy any
layer.CmdPushMatrix = layer.CmdPushMatrix or {}

---@class layer.CmdPushObjectTransformsToMatrix
---@field entity any
layer.CmdPushObjectTransformsToMatrix = layer.CmdPushObjectTransformsToMatrix or {}

---@class layer.CmdRenderBatchFlush
layer.CmdRenderBatchFlush = layer.CmdRenderBatchFlush or {}

---@class layer.CmdRenderNPatchRect
---@field dest any
---@field info any
---@field origin any
---@field rotation any
---@field sourceTexture any
---@field tint any
layer.CmdRenderNPatchRect = layer.CmdRenderNPatchRect or {}

---@class layer.CmdRenderRectVerticesFilledLayer
---@field cache any
---@field color any
---@field outerRec any
---@field progressOrFullBackground any
layer.CmdRenderRectVerticesFilledLayer = layer.CmdRenderRectVerticesFilledLayer or {}

---@class layer.CmdRenderRectVerticesOutlineLayer
---@field cache any
---@field color any
---@field useFullVertices any
layer.CmdRenderRectVerticesOutlineLayer = layer.CmdRenderRectVerticesOutlineLayer or {}

---@class layer.CmdResetShader
layer.CmdResetShader = layer.CmdResetShader or {}

---@class layer.CmdRotate
---@field angle any
layer.CmdRotate = layer.CmdRotate or {}

---@class layer.CmdScale
---@field scaleX any
---@field scaleY any
layer.CmdScale = layer.CmdScale or {}

---@class layer.CmdScopedTransformCompositeRender
---@field entity any
---@field payload any
layer.CmdScopedTransformCompositeRender = layer.CmdScopedTransformCompositeRender or {}

---@class layer.CmdSendUniformFloat
---@field shader any
---@field uniform any
---@field value any
layer.CmdSendUniformFloat = layer.CmdSendUniformFloat or {}

---@class layer.CmdSendUniformFloatArray
---@field shader any
---@field uniform any
---@field values any
layer.CmdSendUniformFloatArray = layer.CmdSendUniformFloatArray or {}

---@class layer.CmdSendUniformInt
---@field shader any
---@field uniform any
---@field value any
layer.CmdSendUniformInt = layer.CmdSendUniformInt or {}

---@class layer.CmdSendUniformIntArray
---@field shader any
---@field uniform any
---@field values any
layer.CmdSendUniformIntArray = layer.CmdSendUniformIntArray or {}

---@class layer.CmdSendUniformVec2
---@field shader any
---@field uniform any
---@field value any
layer.CmdSendUniformVec2 = layer.CmdSendUniformVec2 or {}

---@class layer.CmdSendUniformVec3
---@field shader any
---@field uniform any
---@field value any
layer.CmdSendUniformVec3 = layer.CmdSendUniformVec3 or {}

---@class layer.CmdSendUniformVec4
---@field shader any
---@field uniform any
---@field value any
layer.CmdSendUniformVec4 = layer.CmdSendUniformVec4 or {}

---@class layer.CmdSetBlendMode
---@field blendMode any
layer.CmdSetBlendMode = layer.CmdSetBlendMode or {}

---@class layer.CmdSetColor
---@field color any
layer.CmdSetColor = layer.CmdSetColor or {}

---@class layer.CmdSetLineWidth
---@field lineWidth any
layer.CmdSetLineWidth = layer.CmdSetLineWidth or {}

---@class layer.CmdSetShader
---@field shader any
layer.CmdSetShader = layer.CmdSetShader or {}

---@class layer.CmdSetTexture
---@field texture any
layer.CmdSetTexture = layer.CmdSetTexture or {}

---@class layer.CmdStencilFunc
---@field func any
---@field mask any
---@field ref any
layer.CmdStencilFunc = layer.CmdStencilFunc or {}

---@class layer.CmdStencilOp
---@field dpfail any
---@field dppass any
---@field sfail any
layer.CmdStencilOp = layer.CmdStencilOp or {}

---@class layer.CmdTextPro
---@field color any
---@field font any
---@field fontSize any
---@field origin any
---@field rotation any
---@field spacing any
---@field text any
---@field x any
---@field y any
layer.CmdTextPro = layer.CmdTextPro or {}

---@class layer.CmdTexturePro
---@field color any
---@field offsetX any
---@field offsetY any
---@field rotation any
---@field rotationCenter any
---@field size any
---@field source any
---@field texture any
layer.CmdTexturePro = layer.CmdTexturePro or {}

---@class layer.CmdTranslate
---@field x any
---@field y any
layer.CmdTranslate = layer.CmdTranslate or {}

---@class layer.CmdUnsetBlendMode
---@field dummy any
layer.CmdUnsetBlendMode = layer.CmdUnsetBlendMode or {}

---@class layer.CmdVertex
---@field color any
---@field v any
layer.CmdVertex = layer.CmdVertex or {}

---@class layer.DrawCommandSpace
---@field Screen any
---@field World any
layer.DrawCommandSpace = layer.DrawCommandSpace or {}

---@class layer.DrawCommandType
---@field AddPop any
---@field AddPush any
---@field BeginDrawing any
---@field BeginOpenGLMode any
---@field ClearBackground any
---@field DrawCircle any
---@field DrawDashedLine any
---@field DrawEntityAnimation any
---@field DrawGradientRectCentered any
---@field DrawGradientRectRoundedCentered any
---@field DrawImage any
---@field DrawLine any
---@field DrawPolygon any
---@field DrawRectangle any
---@field DrawRectangleLinesPro any
---@field DrawRectanglePro any
---@field DrawText any
---@field DrawTextCentered any
---@field DrawTransformEntityAnimation any
---@field DrawTransformEntityAnimationPipeline any
---@field DrawTriangle any
---@field EndDrawing any
---@field EndOpenGLMode any
---@field PopMatrix any
---@field PushMatrix any
---@field PushObjectTransformsToMatrix any
---@field RenderNPatchRect any
---@field RenderRectVerticesFilledLayer any
---@field RenderRectVerticesOutlineLayer any
---@field ResetShader any
---@field Rotate any
---@field Scale any
---@field ScopedTransformCompositeRender any
---@field SendUniformFloat any
---@field SendUniformFloatArray any
---@field SendUniformInt any
---@field SendUniformIntArray any
---@field SendUniformVec2 any
---@field SendUniformVec3 any
---@field SendUniformVec4 any
---@field SetBlendMode any
---@field SetColor any
---@field SetLineWidth any
---@field SetShader any
---@field SetTexture any
---@field TextPro any
---@field TexturePro any
---@field Translate any
---@field UnsetBlendMode any
---@field Vertex any
layer.DrawCommandType = layer.DrawCommandType or {}

---@class layer.DrawCommandV2
---@field data any
---@field type any
---@field z any
layer.DrawCommandV2 = layer.DrawCommandV2 or {}

---@class layer.Layer
---@field backgroundColor any
---@field canvases any
---@field commands any
---@field drawCommands any
---@field fixed any
---@field isSorted any
---@field postProcessShaders any
---@field zIndex any
layer.Layer = layer.Layer or {}

---@class layer.LayerOrderComponent
---@field zIndex any
layer.LayerOrderComponent = layer.LayerOrderComponent or {}

---@class layerTbl.CmdResetShader
layerTbl.CmdResetShader = layerTbl.CmdResetShader or {}

---@enum layerTbl.DrawCommandType
layerTbl.DrawCommandType = layerTbl.DrawCommandType or {}

---@class layerTbl.DrawCommandV2
layerTbl.DrawCommandV2 = layerTbl.DrawCommandV2 or {}

---@class layerTbl.Layer
layerTbl.Layer = layerTbl.Layer or {}

---@class layerTbl.LayerOrderComponent
layerTbl.LayerOrderComponent = layerTbl.LayerOrderComponent or {}

---@param ... any
---@return any
function AddCanvasToLayer(...) end

---@param ... any
---@return any
function Begin(...) end

---@param ... any
---@return any
function ClearAllDrawCommands(...) end

---@param ... any
---@return any
function ClearDrawCommands(...) end

---@param ... any
---@return any
function CreateLayer(...) end

---@param ... any
---@return any
function CreateLayerWithSize(...) end

---@param ... any
---@return any
function DrawCanvasOntoOtherLayer(...) end

---@param ... any
---@return any
function DrawCanvasOntoOtherLayerWithShader(...) end

---@param ... any
---@return any
function DrawCanvasToCurrentRenderTargetWithDestRect(...) end

---@param ... any
---@return any
function DrawCanvasToCurrentRenderTargetWithTransform(...) end

---@param ... any
---@return any
function DrawCustomLamdaToSpecificCanvas(...) end

---@param ... any
---@return any
function DrawLayerCommandsToSpecificCanvas(...) end

---@param ... any
---@return any
function DrawTransformEntityWithAnimation(...) end

---@param ... any
---@return any
function DrawTransformEntityWithAnimationWithPipeline(...) end

---@param ... any
---@return any
function End(...) end

---@param ... any
---@return any
function ExecuteScale(...) end

---@param ... any
---@return any
function ExecuteTranslate(...) end

---@param ... any
---@return any
function Rect(...) end

---@param ... any
---@return any
function RemoveCanvas(...) end

---@param ... any
---@return any
function RemoveLayerFromCanvas(...) end

---@param ... any
---@return any
function RenderAllLayersToCurrentRenderTarget(...) end

---@param ... any
---@return any
function ResizeCanvasInLayer(...) end

---@param ... any
---@return any
function SortLayers(...) end

---@param ... any
---@return any
function UnloadAllLayers(...) end

---@param ... any
---@return any
function UpdateLayerZIndex(...) end

---@param ... any
---@return any
function cb.pushEntityTransformsToMatrix(...) end

---@param ... any
---@return any
function cb.queueScopedTransformCompositeRender(...) end

---@param ... any
---@return any
function cb.queueScopedTransformCompositeRenderWithPipeline(...) end

---@param ... any
---@return any
function layerTbl.CreateLayer(...) end

---@param ... any
---@return any
function layerTbl.CreateLayerWithSize(...) end

---@param ... any
---@return any
function layerTbl.RemoveLayerFromCanvas(...) end

---@param ... any
---@return any
function layerTbl.SortLayers(...) end

---@param ... any
---@return any
function layerTbl.UpdateLayerZIndex(...) end

---@param ... any
---@return any
function npatchTbl.new(...) end

---@param ... any
---@return any
function rectTbl.new(...) end

---@param ... any
---@return any
function rectUT.area(...) end

---@param ... any
---@return any
function rectUT.center(...) end

---@param ... any
---@return any
function rectUT.contains(...) end
