---@meta
-- Generated by scripts/generate_stubs.py. DO NOT EDIT BY HAND.

Arbiter = Arbiter or {}
CollisionEvent = CollisionEvent or {}
PhysicsManager = PhysicsManager or {}
PhysicsManagerUD = PhysicsManagerUD or {}
PhysicsWorld = PhysicsWorld or {}
RaycastHit = RaycastHit or {}
physics = physics or {}
physics_table = physics_table or {}
pm = pm or {}
steering = steering or {}
t = t or {}
physics.Arbiter = physics.Arbiter or {}
physics.ColliderShapeType = physics.ColliderShapeType or {}
physics.CollisionEvent = physics.CollisionEvent or {}
physics.PhysicsSyncMode = physics.PhysicsSyncMode or {}
physics.PhysicsWorld = physics.PhysicsWorld or {}
physics.RaycastHit = physics.RaycastHit or {}
physics.RotationSyncMode = physics.RotationSyncMode or {}
physics_table.ColliderShapeType = physics_table.ColliderShapeType or {}
physics_table.PhysicsSyncMode = physics_table.PhysicsSyncMode or {}
physics_table.RotationSyncMode = physics_table.RotationSyncMode or {}

---@class Arbiter
Arbiter = Arbiter or {}

---@class CollisionEvent
CollisionEvent = CollisionEvent or {}

---@class PhysicsManager
PhysicsManager = PhysicsManager or {}

---@class PhysicsManagerUD
---@field add_world any
---@field draw_all any
---@field enable_debug_draw any
---@field enable_step any
---@field find_path any
---@field get_nav_config any
---@field get_world any
---@field has_world any
---@field is_world_active any
---@field mark_navmesh_dirty any
---@field move_entity_to_world any
---@field rebuild_navmesh any
---@field set_nav_config any
---@field set_nav_obstacle any
---@field step_all any
---@field vision_fan any
PhysicsManagerUD = PhysicsManagerUD or {}

---@class PhysicsWorld
PhysicsWorld = PhysicsWorld or {}

---@class RaycastHit
RaycastHit = RaycastHit or {}

---@class physics
physics = physics or {}

---@class physics.Arbiter
physics.Arbiter = physics.Arbiter or {}

---@class physics.ColliderShapeType
physics.ColliderShapeType = physics.ColliderShapeType or {}

---@class physics.CollisionEvent
physics.CollisionEvent = physics.CollisionEvent or {}

---@class physics.PhysicsSyncMode
physics.PhysicsSyncMode = physics.PhysicsSyncMode or {}

---@class physics.PhysicsWorld
physics.PhysicsWorld = physics.PhysicsWorld or {}

---@class physics.RaycastHit
physics.RaycastHit = physics.RaycastHit or {}

---@class physics.RotationSyncMode
physics.RotationSyncMode = physics.RotationSyncMode or {}

---@enum physics_table.ColliderShapeType
physics_table.ColliderShapeType = physics_table.ColliderShapeType or {}

---@enum physics_table.PhysicsSyncMode
physics_table.PhysicsSyncMode = physics_table.PhysicsSyncMode or {}

---@enum physics_table.RotationSyncMode
physics_table.RotationSyncMode = physics_table.RotationSyncMode or {}

---@class steering
steering = steering or {}

---@param world any
---@param e any
---@param tag any
---@param shapeType any
---@param a any
---@param b any
---@param c any
---@param d any
---@param isSensor any
---@param points any
---@return nil
function physics.AddCollider(world, e, tag, shapeType, a, b, c, d, isSensor, points) end

---@param world any
---@param e any
---@param tag any
---@param shapeType any
---@param a any
---@param b any
---@param c any
---@param d any
---@param isSensor any
---@param points any
---@return nil
function physics.add_shape_to_entity(world, e, tag, shapeType, a, b, c, d, isSensor, points) end

---@param p lightuserdata
---@return entt.entity
function physics.entity_from_ptr(p) end

---@param ... any
---@return any
function physics_table.add_bar_segment(...) end

---@param ... any
---@return any
function physics_table.add_damped_rotary_spring(...) end

---@param ... any
---@return any
function physics_table.add_damped_spring(...) end

---@param ... any
---@return any
function physics_table.add_fluid_sensor_aabb(...) end

---@param ... any
---@return any
function physics_table.add_one_way_platform(...) end

---@param ... any
---@return any
function physics_table.add_pin_joint(...) end

---@param ... any
---@return any
function physics_table.add_pivot_joint_world(...) end

---@param ... any
---@return any
function physics_table.add_screen_bounds(...) end

---@param ... any
---@return any
function physics_table.add_slide_joint(...) end

---@param ... any
---@return any
function physics_table.add_smooth_segment_chain(...) end

---@param ... any
---@return any
function physics_table.add_upright_spring(...) end

---@param ... any
---@return any
function physics_table.clear_all_worlds(...) end

---@param ... any
---@return any
function physics_table.clear_pair_handlers(...) end

---@param ... any
---@return any
function physics_table.clear_wildcard_handlers(...) end

---@param ... any
---@return any
function physics_table.command_tank_to(...) end

---@param ... any
---@return any
function physics_table.create_planet(...) end

---@param ... any
---@return any
function physics_table.create_platformer_player(...) end

---@param ... any
---@return any
function physics_table.create_tilemap_colliders(...) end

---@param ... any
---@return any
function physics_table.create_topdown_controller(...) end

---@param ... any
---@return any
function physics_table.crush_on(...) end

---@param ... any
---@return any
function physics_table.cull_entities_outside_bounds(...) end

---@param ... any
---@return any
function physics_table.disable_collision_between(...) end

---@param ... any
---@return any
function physics_table.disable_collision_between_many(...) end

---@param ... any
---@return any
function physics_table.disable_collision_grouping(...) end

---@param ... any
---@return any
function physics_table.disable_custom_gravity(...) end

---@param ... any
---@return any
function physics_table.disable_sticky_between(...) end

---@param ... any
---@return any
function physics_table.disable_trigger_between(...) end

---@param ... any
---@return any
function physics_table.disable_trigger_between_many(...) end

---@param ... any
---@return any
function physics_table.enable_collision_between(...) end

---@param ... any
---@return any
function physics_table.enable_collision_between_many(...) end

---@param ... any
---@return any
function physics_table.enable_collision_grouping(...) end

---@param ... any
---@return any
function physics_table.enable_inverse_square_gravity_to_body(...) end

---@param ... any
---@return any
function physics_table.enable_inverse_square_gravity_to_point(...) end

---@param ... any
---@return any
function physics_table.enable_sticky_between(...) end

---@param ... any
---@return any
function physics_table.enable_tank_controller(...) end

---@param ... any
---@return any
function physics_table.enable_trigger_between(...) end

---@param ... any
---@return any
function physics_table.enable_trigger_between_many(...) end

---@param ... any
---@return any
function physics_table.end_mouse_drag(...) end

---@param ... any
---@return any
function physics_table.enforce_rotation_policy(...) end

---@param ... any
---@return any
function physics_table.get_rotation_mode(...) end

---@param ... any
---@return any
function physics_table.get_sync_mode(...) end

---@param ... any
---@return any
function physics_table.make_breakable_slide_joint(...) end

---@param ... any
---@return any
function physics_table.make_constraint_breakable(...) end

---@param ... any
---@return any
function physics_table.on_pair_begin(...) end

---@param ... any
---@return any
function physics_table.on_pair_postsolve(...) end

---@param ... any
---@return any
function physics_table.on_pair_presolve(...) end

---@param ... any
---@return any
function physics_table.on_pair_separate(...) end

---@param ... any
---@return any
function physics_table.on_wildcard_begin(...) end

---@param ... any
---@return any
function physics_table.on_wildcard_postsolve(...) end

---@param ... any
---@return any
function physics_table.on_wildcard_presolve(...) end

---@param ... any
---@return any
function physics_table.on_wildcard_separate(...) end

---@param ... any
---@return any
function physics_table.point_query_nearest(...) end

---@param ... any
---@return any
function physics_table.reapply_all_filters(...) end

---@param ... any
---@return any
function physics_table.register_fluid_volume(...) end

---@param ... any
---@return any
function physics_table.remove_physics(...) end

---@param ... any
---@return any
function physics_table.segment_query_first(...) end

---@param ... any
---@return any
function physics_table.set_circular_orbit_velocity(...) end

---@param ... any
---@return any
function physics_table.set_collision_tags(...) end

---@param ... any
---@return any
function physics_table.set_constraint_limits(...) end

---@param ... any
---@return any
function physics_table.set_platformer_input(...) end

---@param ... any
---@return any
function physics_table.set_rotation_mode(...) end

---@param ... any
---@return any
function physics_table.set_sensor(...) end

---@param ... any
---@return any
function physics_table.set_sync_mode(...) end

---@param ... any
---@return any
function physics_table.shatter_nearest(...) end

---@param ... any
---@return any
function physics_table.slice_first_hit(...) end

---@param ... any
---@return any
function physics_table.spawn_orbiting_box(...) end

---@param ... any
---@return any
function physics_table.start_mouse_drag(...) end

---@param ... any
---@return any
function physics_table.total_force_on(...) end

---@param ... any
---@return any
function physics_table.touching_entities(...) end

---@param ... any
---@return any
function physics_table.update_collision_masks_for(...) end

---@param ... any
---@return any
function physics_table.update_mouse_drag(...) end

---@param ... any
---@return any
function physics_table.update_tanks(...) end

---@param ... any
---@return any
function physics_table.use_physics_free_rotation(...) end

---@param ... any
---@return any
function physics_table.use_transform_fixed_rotation(...) end

---@param ... any
---@return any
function physics_table.weight_on(...) end

---@param ... any
---@return any
function pm.add_world(...) end

---@param ... any
---@return any
function pm.draw_all(...) end

---@param ... any
---@return any
function pm.enable_debug_draw(...) end

---@param ... any
---@return any
function pm.enable_step(...) end

---@param ... any
---@return any
function pm.find_path(...) end

---@param ... any
---@return any
function pm.get_nav_config(...) end

---@param ... any
---@return any
function pm.get_world(...) end

---@param ... any
---@return any
function pm.has_world(...) end

---@param ... any
---@return any
function pm.is_world_active(...) end

---@param ... any
---@return any
function pm.mark_navmesh_dirty(...) end

---@param ... any
---@return any
function pm.move_entity_to_world(...) end

---@param ... any
---@return any
function pm.rebuild_navmesh(...) end

---@param ... any
---@return any
function pm.set_nav_config(...) end

---@param ... any
---@return any
function pm.set_nav_obstacle(...) end

---@param ... any
---@return any
function pm.step_all(...) end

---@param ... any
---@return any
function pm.vision_fan(...) end

---@param ... any
---@return any
function t.arb_get_bool(...) end

---@param ... any
---@return any
function t.arb_get_number(...) end

---@param ... any
---@return any
function t.arb_get_ptr(...) end

---@param ... any
---@return any
function t.arb_set_bool(...) end

---@param ... any
---@return any
function t.arb_set_number(...) end

---@param ... any
---@return any
function t.arb_set_ptr(...) end
