---@meta
-- Generated by scripts/generate_stubs.py. DO NOT EDIT BY HAND.

sh = sh or {}
shaders = shaders or {}
sp = sp or {}
sh.ShaderUniformComponent = sh.ShaderUniformComponent or {}
sh.ShaderUniformSet = sh.ShaderUniformSet or {}
shaders.ShaderUniformComponent = shaders.ShaderUniformComponent or {}
shaders.ShaderUniformSet = shaders.ShaderUniformSet or {}

---@class sh.ShaderUniformComponent
sh.ShaderUniformComponent = sh.ShaderUniformComponent or {}

---@class sh.ShaderUniformSet
sh.ShaderUniformSet = sh.ShaderUniformSet or {}

---@class shaders
shaders = shaders or {}

---@class shaders.ShaderUniformComponent
shaders.ShaderUniformComponent = shaders.ShaderUniformComponent or {}

---@class shaders.ShaderUniformSet
shaders.ShaderUniformSet = shaders.ShaderUniformSet or {}

---@param ... any
---@return any
function TryApplyUniforms(...) end

---@param ... any
---@return any
function addShaderPass(...) end

---@param ... any
---@return any
function addShaderPreset(...) end

---@param ... any
---@return any
function applyShaderPreset(...) end

---@param ... any
---@return any
function clearShaderPasses(...) end

---@param ... any
---@return any
function setSkipBaseSprite(...) end

---@param ... any
---@return any
function sh.ApplyUniformsToShader(...) end

---@param ... any
---@return any
function sh.ShowShaderEditorUI(...) end

---@param ... any
---@return any
function sh.disableAllShadersViaOverride(...) end

---@param ... any
---@return any
function sh.getShader(...) end

---@param ... any
---@return any
function sh.hotReloadShaders(...) end

---@param ... any
---@return any
function sh.loadShadersFromJSON(...) end

---@param ... any
---@return any
function sh.registerUniformUpdate(...) end

---@param ... any
---@return any
function sh.setShaderMode(...) end

---@param ... any
---@return any
function sh.unloadShaders(...) end

---@param ... any
---@return any
function sh.unsetShaderMode(...) end

---@param ... any
---@return any
function sh.updateAllShaderUniforms(...) end

---@param ... any
---@return any
function sh.updateShaders(...) end

---@param ... any
---@return any
function sp.getPresetNames(...) end

---@param ... any
---@return any
function sp.hasPreset(...) end

---@param ... any
---@return any
function sp.loadFromFile(...) end
