---@meta
-- Generated by scripts/generate_stubs.py. DO NOT EDIT BY HAND.

---@param ... any
---@return any
function clearPlaylist(...) end

---@param ... any
---@return any
function fadeInMusic(...) end

---@param ... any
---@return any
function fadeOutMusic(...) end

---@param ... any
---@return any
function getTrackVolume(...) end

---@param ... any
---@return any
function pauseMusic(...) end

---@param ... any
---@return any
function playMusic(...) end

---@param ... any
---@return any
function playPlaylist(...) end

---@param ... any
---@return any
function playSoundEffect(...) end

---@param ... any
---@return any
function queueMusic(...) end

---@param ... any
---@return any
function resetSoundSystem(...) end

---@param ... any
---@return any
function resumeMusic(...) end

---@param ... any
---@return any
function setCategoryVolume(...) end

---@param ... any
---@return any
function setLowPassSpeed(...) end

---@param ... any
---@return any
function setLowPassTarget(...) end

---@param ... any
---@return any
function setMusicVolume(...) end

---@param ... any
---@return any
function setSoundPitch(...) end

---@param ... any
---@return any
function setTrackVolume(...) end

---@param ... any
---@return any
function setVolume(...) end

---@param ... any
---@return any
function stopAllMusic(...) end

---@param ... any
---@return any
function toggleDelayEffect(...) end

---@param ... any
---@return any
function toggleLowPassFilter(...) end
