---@meta
-- Generated by scripts/generate_stubs.py. DO NOT EDIT BY HAND.

AnimationQueueComponent = AnimationQueueComponent or {}
EventQueueSystem = EventQueueSystem or {}
animation_system = animation_system or {}
timer = timer or {}
EventQueueSystem.ConditionData = EventQueueSystem.ConditionData or {}
EventQueueSystem.EaseData = EventQueueSystem.EaseData or {}
EventQueueSystem.EaseDataBuilder = EventQueueSystem.EaseDataBuilder or {}
EventQueueSystem.EaseType = EventQueueSystem.EaseType or {}
EventQueueSystem.Event = EventQueueSystem.Event or {}
EventQueueSystem.EventBuilder = EventQueueSystem.EventBuilder or {}
EventQueueSystem.TimerType = EventQueueSystem.TimerType or {}
EventQueueSystem.TriggerType = EventQueueSystem.TriggerType or {}
timer.TimerType = timer.TimerType or {}
timer.math = timer.math or {}

---@class AnimationQueueComponent
AnimationQueueComponent = AnimationQueueComponent or {}

---@class EventQueueSystem
EventQueueSystem = EventQueueSystem or {}

---@class EventQueueSystem.ConditionData
---@field check any
EventQueueSystem.ConditionData = EventQueueSystem.ConditionData or {}

---@class EventQueueSystem.EaseData
---@field endTime any
---@field endValue any
---@field getValueCallback any
---@field setValueCallback any
---@field startTime any
---@field startValue any
---@field type any
EventQueueSystem.EaseData = EventQueueSystem.EaseData or {}

---@class EventQueueSystem.EaseDataBuilder
EventQueueSystem.EaseDataBuilder = EventQueueSystem.EaseDataBuilder or {}

---@class EventQueueSystem.EaseType
---@field ELASTIC_IN any
---@field ELASTIC_OUT any
---@field LERP any
---@field QUAD_IN any
---@field QUAD_OUT any
EventQueueSystem.EaseType = EventQueueSystem.EaseType or {}

---@class EventQueueSystem.Event
---@field blocksQueue any
---@field canBeBlocked any
---@field complete any
---@field condition any
---@field createdWhilePaused any
---@field debugID any
---@field delaySeconds any
---@field deleteNextCycleImmediately any
---@field ease any
---@field eventTrigger any
---@field func any
---@field retainAfterCompletion any
---@field tag any
---@field time any
---@field timerStarted any
---@field timerType any
EventQueueSystem.Event = EventQueueSystem.Event or {}

---@class EventQueueSystem.EventBuilder
EventQueueSystem.EventBuilder = EventQueueSystem.EventBuilder or {}

---@class EventQueueSystem.TimerType
---@field REAL_TIME any
---@field TOTAL_TIME_EXCLUDING_PAUSE any
EventQueueSystem.TimerType = EventQueueSystem.TimerType or {}

---@class EventQueueSystem.TriggerType
---@field AFTER any
---@field BEFORE any
---@field CONDITION any
---@field EASE any
---@field IMMEDIATE any
EventQueueSystem.TriggerType = EventQueueSystem.TriggerType or {}

---@class animation_system
animation_system = animation_system or {}

---@class timer
timer = timer or {}

---@class timer.TimerType
---@field AFTER any
---@field COOLDOWN any
---@field EVERY any
---@field EVERY_RENDER_FRAME_ONLY any
---@field EVERY_STEP any
---@field FOR any
---@field RUN any
---@field TWEEN any
timer.TimerType = timer.TimerType or {}

---@class timer.math
timer.math = timer.math or {}

---@param ... any
---@return any
function EventQueueSystem.add_event(...) end

---@param ... any
---@return any
function EventQueueSystem.clear_queue(...) end

---@param ... any
---@return any
function EventQueueSystem.get_event_by_tag(...) end

---@param ... any
---@return any
function EventQueueSystem.update(...) end

---@param ... any
---@return any
function animation_system.clearCallbacks(...) end

---@param ... any
---@return any
function animation_system.createAnimatedObjectWithTransform(...) end

---@param ... any
---@return any
function animation_system.createStillAnimationFromSpriteUUID(...) end

---@param ... any
---@return any
function animation_system.getCurrentFrame(...) end

---@param ... any
---@return any
function animation_system.getFrameCount(...) end

---@param ... any
---@return any
function animation_system.getNinepatchUIBorderInfo(...) end

---@param ... any
---@return any
function animation_system.getProgress(...) end

---@param ... any
---@return any
function animation_system.isPlaying(...) end

---@param ... any
---@return any
function animation_system.onAnimationEnd(...) end

---@param ... any
---@return any
function animation_system.onFrameChange(...) end

---@param ... any
---@return any
function animation_system.onLoopComplete(...) end

---@param ... any
---@return any
function animation_system.pause(...) end

---@param ... any
---@return any
function animation_system.play(...) end

---@param ... any
---@return any
function animation_system.replaceAnimatedObjectOnEntity(...) end

---@param ... any
---@return any
function animation_system.resetAnimationUIRenderScale(...) end

---@param ... any
---@return any
function animation_system.resizeAnimationObjectToFit(...) end

---@param ... any
---@return any
function animation_system.resizeAnimationObjectsInEntityToFit(...) end

---@param ... any
---@return any
function animation_system.resizeAnimationObjectsInEntityToFitAndCenterUI(...) end

---@param ... any
---@return any
function animation_system.seekFrame(...) end

---@param ... any
---@return any
function animation_system.setDirection(...) end

---@param ... any
---@return any
function animation_system.setFGColorForAllAnimationObjects(...) end

---@param ... any
---@return any
function animation_system.setLoopCount(...) end

---@param ... any
---@return any
function animation_system.setSpeed(...) end

---@param ... any
---@return any
function animation_system.set_flip(...) end

---@param ... any
---@return any
function animation_system.set_horizontal_flip(...) end

---@param ... any
---@return any
function animation_system.setupAnimatedObjectOnEntity(...) end

---@param ... any
---@return any
function animation_system.stop(...) end

---@param ... any
---@return any
function animation_system.toggle_flip(...) end

---@param ... any
---@return any
function animation_system.update(...) end

---@param ... any
---@return any
function timer.after(...) end

---@param ... any
---@return any
function timer.cancel(...) end

---@param ... any
---@return any
function timer.clear_all(...) end

---@param ... any
---@return any
function timer.cooldown(...) end

---@param ... any
---@return any
function timer.every(...) end

---@param ... any
---@return any
function timer.every_step(...) end

---@param ... any
---@return any
function timer.for_time(...) end

---@param ... any
---@return any
function timer.get_delay(...) end

---@param ... any
---@return any
function timer.get_every_index(...) end

---@param ... any
---@return any
function timer.get_for_elapsed(...) end

---@param ... any
---@return any
function timer.get_multiplier(...) end

---@param ... any
---@return any
function timer.get_timer_and_delay(...) end

---@param ... any
---@return any
function timer.kill_group(...) end

---@param ... any
---@return any
function timer.math.lerp(...) end

---@param ... any
---@return any
function timer.math.remap(...) end

---@param ... any
---@return any
function timer.pause(...) end

---@param ... any
---@return any
function timer.pause_group(...) end

---@param ... any
---@return any
function timer.reset(...) end

---@param ... any
---@return any
function timer.resume(...) end

---@param ... any
---@return any
function timer.resume_group(...) end

---@param ... any
---@return any
function timer.run(...) end

---@param ... any
---@return any
function timer.run_every_render_frame(...) end

---@param ... any
---@return any
function timer.set_multiplier(...) end

---@param ... any
---@return any
function timer.tween(...) end

---@param ... any
---@return any
function timer.update(...) end
