---@meta
-- Generated by scripts/generate_stubs.py. DO NOT EDIT BY HAND.

FocusArgs = FocusArgs or {}
InventoryGridTileComponent = InventoryGridTileComponent or {}
ObjectAttachedToUITag = ObjectAttachedToUITag or {}
PackHandle = PackHandle or {}
SliderComponent = SliderComponent or {}
SpriteScaleMode = SpriteScaleMode or {}
TextInput = TextInput or {}
TextInputHook = TextInputHook or {}
Tooltip = Tooltip or {}
UIBoxComponent = UIBoxComponent or {}
UIConfig = UIConfig or {}
UIConfigBuilder = UIConfigBuilder or {}
UIConfigBundle = UIConfigBundle or {}
UIContentConfig = UIContentConfig or {}
UIDecoration = UIDecoration or {}
UIDecorationAnchor = UIDecorationAnchor or {}
UIDecorations = UIDecorations or {}
UIElementComponent = UIElementComponent or {}
UIElementCore = UIElementCore or {}
UIElementTemplateNode = UIElementTemplateNode or {}
UIElementTemplateNodeBuilder = UIElementTemplateNodeBuilder or {}
UIInteractionConfig = UIInteractionConfig or {}
UILayoutConfig = UILayoutConfig or {}
UIState = UIState or {}
UIStyleConfig = UIStyleConfig or {}
UIStylingType = UIStylingType or {}
UITypeEnum = UITypeEnum or {}
ui = ui or {}
ui.box = ui.box or {}
ui.element = ui.element or {}

---@class FocusArgs
---@field button any
---@field claim_focus_from any
---@field nav any
---@field no_loop any
---@field redirect_focus_to any
---@field registered any
---@field snap_to any
---@field type any
FocusArgs = FocusArgs or {}

---@class InventoryGridTileComponent
---@field item any
InventoryGridTileComponent = InventoryGridTileComponent or {}

---@class ObjectAttachedToUITag
ObjectAttachedToUITag = ObjectAttachedToUITag or {}

---@class PackHandle
PackHandle = PackHandle or {}

---@class SliderComponent
---@field color any
---@field decimal_places any
---@field h any
---@field max any
---@field min any
---@field text any
---@field value any
---@field w any
SliderComponent = SliderComponent or {}

---@class SpriteScaleMode
---@field Fixed any
---@field Stretch any
---@field Tile any
SpriteScaleMode = SpriteScaleMode or {}

---@class TextInput
---@field allCaps any
---@field callback any
---@field cursorPos any
---@field maxLength any
---@field text any
TextInput = TextInput or {}

---@class TextInputHook
---@field hookedEntity any
TextInputHook = TextInputHook or {}

---@class Tooltip
---@field text any
---@field title any
Tooltip = Tooltip or {}

---@class UIBoxComponent
---@field drawLayers any
---@field onBoxResize any
---@field uiRoot any
UIBoxComponent = UIBoxComponent or {}

---@class UIConfig
---@field alignmentFlags any
---@field buttonCallback any
---@field buttonClicked any
---@field buttonDelay any
---@field buttonDelayEnd any
---@field buttonDelayProgress any
---@field buttonDelayStart any
---@field buttonDistance any
---@field buttonTemp any
---@field button_UIE any
---@field canCollide any
---@field choice any
---@field chosen any
---@field chosen_vert any
---@field collideable any
---@field color any
---@field computedFillSize any
---@field dPopup any
---@field dPopupConfig any
---@field detailedTooltip any
---@field disable_button any
---@field drawLayer any
---@field draw_after any
---@field dynamicMotion any
---@field emboss any
---@field extend_up any
---@field flexWeight any
---@field focusArgs any
---@field focusWithObject any
---@field fontName any
---@field fontSize any
---@field forceCollision any
---@field force_focus any
---@field group any
---@field groupParent any
---@field hPopup any
---@field hPopupConfig any
---@field height any
---@field hover any
---@field id any
---@field initFunc any
---@field instaFunc any
---@field instanceType any
---@field isFiller any
---@field language any
---@field line_emboss any
---@field location_bond any
---@field makeMovementDynamic any
---@field master any
---@field maxFillSize any
---@field maxHeight any
---@field maxWidth any
---@field mid any
---@field minHeight any
---@field minWidth any
---@field nPatchInfo any
---@field nPatchSourceTexture any
---@field noFill any
---@field noMovementWhenDragged any
---@field noRole any
---@field no_recalc any
---@field non_recalc any
---@field object any
---@field objectRecalculate any
---@field offset any
---@field onDemandTooltip any
---@field onUIResizeFunc any
---@field onUIScalingResetToOne any
---@field one_press any
---@field outlineColor any
---@field outlineShadow any
---@field outlineThickness any
---@field padding any
---@field parent any
---@field pixelatedRectangle any
---@field prev_ref_value any
---@field progressBar any
---@field progressBarEmptyColor any
---@field progressBarFetchValueLambda any
---@field progressBarFullColor any
---@field progressBarMaxValue any
---@field progressBarValueComponentName any
---@field progressBarValueFieldName any
---@field ref_component any
---@field ref_entity any
---@field ref_value any
---@field refreshMovement any
---@field resolution any
---@field role any
---@field rotation_bond any
---@field scale any
---@field scale_bond any
---@field shadow any
---@field shadowColor any
---@field size_bond any
---@field spriteScaleMode any
---@field spriteSourceRect any
---@field spriteSourceTexture any
---@field stylingType any
---@field text any
---@field textGetter any
---@field textSpacing any
---@field tooltip any
---@field uiType any
---@field ui_object_updated any
---@field updateFunc any
---@field verticalText any
---@field width any
UIConfig = UIConfig or {}

---@class UIConfigBuilder
UIConfigBuilder = UIConfigBuilder or {}

---@class UIConfigBundle
---@field content any
---@field interaction any
---@field layout any
---@field style any
UIConfigBundle = UIConfigBundle or {}

---@class UIContentConfig
---@field fontName any
---@field fontSize any
---@field instanceType any
---@field language any
---@field object any
---@field objectRecalculate any
---@field progressBar any
---@field progressBarMaxValue any
---@field ref_entity any
---@field text any
---@field textGetter any
---@field verticalText any
UIContentConfig = UIContentConfig or {}

---@class UIDecoration
---@field anchor any
---@field flipX any
---@field flipY any
---@field id any
---@field offset any
---@field opacity any
---@field rotation any
---@field scale any
---@field spriteName any
---@field tint any
---@field visible any
---@field zOffset any
UIDecoration = UIDecoration or {}

---@class UIDecorationAnchor
---@field BottomCenter any
---@field BottomLeft any
---@field BottomRight any
---@field Center any
---@field MiddleLeft any
---@field MiddleRight any
---@field TopCenter any
---@field TopLeft any
---@field TopRight any
UIDecorationAnchor = UIDecorationAnchor or {}

---@class UIDecorations
---@field items any
UIDecorations = UIDecorations or {}

---@class UIElementComponent
---@field UIT any
---@field config any
---@field uiBox any
UIElementComponent = UIElementComponent or {}

---@class UIElementCore
---@field id any
---@field treeOrder any
---@field type any
---@field uiBox any
UIElementCore = UIElementCore or {}

---@class UIElementTemplateNode
---@field children any
---@field config any
---@field type any
UIElementTemplateNode = UIElementTemplateNode or {}

---@class UIElementTemplateNodeBuilder
UIElementTemplateNodeBuilder = UIElementTemplateNodeBuilder or {}

---@class UIInteractionConfig
---@field buttonCallback any
---@field buttonClicked any
---@field canCollide any
---@field choice any
---@field disable_button any
---@field dynamicMotion any
---@field focusArgs any
---@field force_focus any
---@field hover any
---@field tooltip any
---@field updateFunc any
UIInteractionConfig = UIInteractionConfig or {}

---@class UILayoutConfig
---@field alignmentFlags any
---@field draw_after any
---@field height any
---@field maxHeight any
---@field maxWidth any
---@field mid any
---@field minHeight any
---@field minWidth any
---@field offset any
---@field padding any
---@field scale any
---@field width any
UILayoutConfig = UILayoutConfig or {}

---@class UIState
---@field contentDimensions any
---@field focus_timer any
---@field last_clicked any
---@field object_focus_timer any
---@field textDrawable any
UIState = UIState or {}

---@class UIStyleConfig
---@field color any
---@field noFill any
---@field outlineColor any
---@field outlineThickness any
---@field pixelatedRectangle any
---@field shadow any
---@field shadowColor any
---@field stylingType any
UIStyleConfig = UIStyleConfig or {}

---@class UIStylingType
---@field NinePatchBorders any
---@field RoundedRectangle any
---@field Sprite any
UIStylingType = UIStylingType or {}

---@enum UITypeEnum
---@field FILLER any
---@field HORIZONTAL_CONTAINER any
---@field INPUT_TEXT any
---@field NONE any
---@field OBJECT any
---@field RECT_SHAPE any
---@field ROOT any
---@field SCROLL_PANE any
---@field SLIDER_UI any
---@field TEXT any
---@field VERTICAL_CONTAINER any
UITypeEnum = UITypeEnum or {}

---@class ui
ui = ui or {}

---@class ui.box
ui.box = ui.box or {}

---@class ui.element
ui.element = ui.element or {}

---@param ... any
---@return any
function ui.box.AddChild(...) end

---@param ... any
---@return any
function ui.box.AddStateTagToUIBox(...) end

---@param ... any
---@return any
function ui.box.AddTemplateToUIBox(...) end

---@param ... any
---@return any
function ui.box.AssignLayerOrderComponents(...) end

---@param ... any
---@return any
function ui.box.AssignStateTagsToUIBox(...) end

---@param ... any
---@return any
function ui.box.AssignTreeOrderComponents(...) end

---@param ... any
---@return any
function ui.box.BuildUIElementTree(...) end

---@param ... any
---@return any
function ui.box.CalcTreeSizes(...) end

---@param ... any
---@return any
function ui.box.ClampDimensionsToMinimumsIfPresent(...) end

---@param ... any
---@return any
function ui.box.ClearStateTagsFromUIBox(...) end

---@param ... any
---@return any
function ui.box.DebugPrint(...) end

---@param ... any
---@return any
function ui.box.Drag(...) end

---@param ... any
---@return any
function ui.box.GetGroup(...) end

---@param ... any
---@return any
function ui.box.GetUIEByID(...) end

---@param ... any
---@return any
function ui.box.Initialize(...) end

---@param ... any
---@return any
function ui.box.Move(...) end

---@param ... any
---@return any
function ui.box.Recalculate(...) end

---@param ... any
---@return any
function ui.box.Remove(...) end

---@param ... any
---@return any
function ui.box.RemoveGroup(...) end

---@param ... any
---@return any
function ui.box.RenewAlignment(...) end

---@param ... any
---@return any
function ui.box.ReplaceChildren(...) end

---@param ... any
---@return any
function ui.box.SetContainer(...) end

---@param ... any
---@return any
function ui.box.SubCalculateContainerSize(...) end

---@param ... any
---@return any
function ui.box.TraverseUITreeBottomUp(...) end

---@param ... any
---@return any
function ui.box.TreeCalcSubContainer(...) end

---@param ... any
---@return any
function ui.box.TreeCalcSubNonContainer(...) end

---@param ... any
---@return any
function ui.box.buildUIBoxDrawList(...) end

---@param ... any
---@return any
function ui.box.drawAllBoxes(...) end

---@param ... any
---@return any
function ui.box.handleAlignment(...) end

---@param ... any
---@return any
function ui.box.placeNonContainerUIE(...) end

---@param ... any
---@return any
function ui.box.placeUIElementsRecursively(...) end

---@param ... any
---@return any
function ui.box.set_draw_layer(...) end

---@param ... any
---@return any
function ui.element.ApplyAlignment(...) end

---@param ... any
---@return any
function ui.element.ApplyHover(...) end

---@param ... any
---@return any
function ui.element.ApplyScalingToSubtree(...) end

---@param ... any
---@return any
function ui.element.BuildUIDrawList(...) end

---@param ... any
---@return any
function ui.element.CanBeDragged(...) end

---@param ... any
---@return any
function ui.element.Click(...) end

---@param ... any
---@return any
function ui.element.CollidesWithPoint(...) end

---@param ... any
---@return any
function ui.element.DebugPrintTree(...) end

---@param ... any
---@return any
function ui.element.DrawSelf(...) end

---@param ... any
---@return any
function ui.element.Initialize(...) end

---@param ... any
---@return any
function ui.element.InitializeVisualTransform(...) end

---@param ... any
---@return any
function ui.element.JuiceUp(...) end

---@param ... any
---@return any
function ui.element.PutFocusedCursor(...) end

---@param ... any
---@return any
function ui.element.Release(...) end

---@param ... any
---@return any
function ui.element.Remove(...) end

---@param ... any
---@return any
function ui.element.SetAlignments(...) end

---@param ... any
---@return any
function ui.element.SetValues(...) end

---@param ... any
---@return any
function ui.element.SetWH(...) end

---@param ... any
---@return any
function ui.element.StopHover(...) end

---@param ... any
---@return any
function ui.element.Update(...) end

---@param ... any
---@return any
function ui.element.UpdateObject(...) end

---@param ... any
---@return any
function ui.element.UpdateText(...) end

---@param ... any
---@return any
function ui.element.UpdateUIObjectScalingAndRecenter(...) end

---@param ... any
---@return any
function ui.register_pack(...) end

---@param ... any
---@return any
function ui.use_pack(...) end
